/*
 * Author: Mohamed Lamine KARAOUI
 */

#include <stdio.h>
#include "hist.h"                       /* generated by rpcgen */
#include <errno.h>
 
main(argc, argv)
	int argc;
	char *argv[];
{
	CLIENT *clnt;
	int *add_res;
	char *server;
	struct add_arg_s aa;
	struct query_arg_s qa;
	struct query_res_s *qr;

 	if (argc != 5) {
		fprintf(stderr, "usage: %s host day month event\n",argv[0]);
		exit(1);
	}

	server = argv[1];

	/* ADD op arguments */
	aa.date.day = atoi(argv[2]);
	aa.date.month = atoi(argv[3]);
	aa.desc = argv[4];

	/* Query op arguments */
	qa.id = 0;
	qa.date.day = 0;
	qa.date.month = 0;

	/*
	 * Create client "handle" used for
 	 * calling MESSAGEPROG on the server
 	 * designated on the command line.
	 */
	clnt = clnt_create(server, HISTPROG, HISTVERS, "tcp");
	if (clnt == (CLIENT *)NULL) {
		clnt_pcreateerror(server);
		exit(1);
	}

	/* Adding a new event */
	add_res = add_1(&aa, clnt);
	if (!add_res) {
		clnt_perror(clnt, server);
		exit(1);
	}


	/* Query a new event */
	qr = query_1(&qa, clnt);
	if (!qr) {
		clnt_perror(clnt, server);
		exit(1);
	}

	/* Okay, we successfully called
 	 * the remote procedure.
	 */
	if (qr->error != 0) {
	/* Remote system error. Print
	* error message and die.
    	*/
		errno = qr->error;
		perror("query");
		exit(1);
	}
	printf("event returned: id %d, desc %s\n", qr->id, qr->desc);

	xdr_free((xdrproc_t)xdr_query_res_s, (char*)qr);
	clnt_destroy(clnt);
	exit(0);
}
